version: '3.3'

services:
  # Nginx 웹 서버 서비스
  nginx:
    image: nginx:stable-alpine
    container_name: my_nginx
    ports:
      - "8080:80"
      - "8443:443" # HTTPS 포트 추가
    volumes:
      - ./src:/var/www/html
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./nginx/ssl:/etc/nginx/ssl # SSL 인증서 및 키 마운트
    depends_on:
      - php

  # PHP-FPM 서비스
  php:
    build:
      context: .
      dockerfile: php.Dockerfile
    container_name: my_php
    environment:
      MYSQL_DATABASE: 'my_database'
      MYSQL_USER: 'my_user'
      MYSQL_PASSWORD: 'my_password'
    volumes:
      - ./src:/var/www/html
    depends_on:
      db:
        condition: service_healthy

  # MariaDB 데이터베이스 서비스
  db:
    image: mariadb:10.6
    container_name: my_db
    restart: always
    environment:
      MYSQL_DATABASE: 'my_database'      # 생성할 데이터베이스 이름
      MYSQL_USER: 'my_user'              # 데이터베이스 사용자
      MYSQL_PASSWORD: 'my_password'      # 사용자 비밀번호
      MYSQL_ROOT_PASSWORD: 'my_root_password' # root 계정 비밀번호
    volumes:
      - db_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 20s
      retries: 10

volumes:
  db_data: # 데이터베이스 데이터를 영구적으로 저장하기 위한 볼륨
